# Use the official MySQL image
FROM mysql:8.0

# Add custom SQL script to the container for initialization
COPY ./kubernetes/containers/init.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
