FROM golang:1.23-alpine3.20 as builder

WORKDIR /topology-deployer
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /topology-deployer/api-server

FROM alpine:3.20

WORKDIR /topology-deployer
COPY --from=builder /topology-deployer/api-server .
COPY kubernetes/containers/start-server.sh .
RUN mkdir -p configs
RUN chmod +x /topology-deployer/start-server.sh

EXPOSE 5000

CMD ["/topology-deployer/start-server.sh"]
