#!/bin/bash

sudo apt-get update

# Required packages for kvm
sudo apt-get install -y \
    bridge-utils \
    cloud-utils \
    cpu-checker \
    libvirt-clients \
    libvirt-daemon \
    qemu \
    qemu-kvm \
    libvirt-dev \
    libvirt-daemon-system \
    libguestfs-tools \
    virt-manager \
    libosinfo-bin \
    iptables-persistent \
    python3-dev \
    python3-pip

pip3 install libvirt-python

sudo usermod -a -G libvirt $USER
sudo usermod -a -G libvirt-qemu $USER

sudo mkdir -p /var/lib/libvirt/images/templates

wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
sudo mv -i jammy-server-cloudimg-amd64.img \
    /var/lib/libvirt/images/templates/ubuntu-22.04-server.qcow2

wget https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2
sudo mv -i Rocky-8-GenericCloud-Base.latest.x86_64.qcow2 \
    /var/lib/libvirt/images/templates/rocky-8.qcow2

virsh net-destroy default
virsh net-autostart --disable default

sudo pip3 install .
