apiVersion: v1
kind: PersistentVolume
metadata:
  name: td-pv
  namespace: topology-deployer
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/topology-deployer/mysql  # Ensure this path exists on the node
  storageClassName: manual  # Match this with PVC's StorageClass if needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: td-mysql-pvc
  namespace: topology-deployer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # Match this with PV's StorageClass if needed
