# Build stage
FROM node:20.17.0-alpine3.20 as build-stage

WORKDIR /topology-deployer

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --verbose

# Copy the rest of the application files to the working directory
COPY . .

# Build the React application
RUN npm run build

# Production Stage
FROM nginx:latest

# Copy the NGINX configuration file
COPY kubernetes/containers/nginx.conf /etc/nginx/conf.d/default.conf

# Copy the build artifacts from the build stage to NGINX web server
COPY --from=build-stage /topology-deployer/build/ /usr/share/nginx/html

WORKDIR /topology-deployer

RUN touch /var/run/nginx.pid

# Expose port 80 for the NGINX server
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
